#!/bin/bash

case "$1" in
    --add)
        gcc -o manager add_treasure.c
        ./manager "$2"
        ;;
    --list)
        gcc -o manager list_hunt.c
        ./manager "$2"
        ;;
    --view)
        gcc -o manager view_treasure.c
        ./manager "$2" "$3"
        ;;
    --remove)
        if [ $# -eq 3 ]; then
            gcc -o manager remove_treasure.c
            ./manager "$2" "$3"
        elif [ $# -eq 2 ]; then
            gcc -o manager remove_hunt.c
            ./manager "$2"
        fi
        ;;
    --score)
        gcc -o manager calculate_score.c
        ./manager "$2"
        ;;
    *)
        echo "Comandă necunoscută."
        ;;
esac

rm manager