#!/bin/bash

case "$1" in
    --add)
        gcc -o run add_treasure.c
        ./run "$2"
        ;;
    --list)
        gcc -o run list_hunt.c
        ./run "$2"
        ;;
    --view)
        gcc -o run view_treasure.c
        ./run "$2" "$3"
        ;;
    --remove)
        if [ $# -eq 3 ]; then
            gcc -o run remove_treasure.c
            ./run "$2" "$3"
        elif [ $# -eq 2 ]; then
            gcc -o run remove_hunt.c
            ./run "$2"
        fi
        ;;
    *)
        echo "Comandă necunoscută."
        ;;
esac

rm run